language: node_js
node_js:
- 12
addons:
  browserstack:
    username: januszjan1
    acces_key:
      secure: f+8qmvV8Ar3xaDzfmn3r67n/VgfvBhB0ZlOgq9rYiNgB7E6XaKSkOqf3Jmq8SH0gfvPapmJPWfRMbR2lz89RQUTpwK+vUIWT9xaZ8XoTIhgnMjrUlbOZHF97YyvhG7ajWwpPASsbSvZ6IHZNnnmNyhj1OgmuduGvPoSdjm6dCijnMPosGLN7C9+cmxx71YznEMJZJ9238mrcniZ8fdV06fDp9NN522SecJxP84o4As4iKmkWy/pkKT4JpOvdfMK8g8yhXmhFvReZkx6SsHj8G10qFoRF12Z52ywH641eWEbdkKvqayY1v4TuJWGVVRD89MKRblTR0IvlifnSxPlhJaqQRarjgNk88oOnIVvbkAEmXTlDPvKpFFCHdVq4d/p6/kuyfwLJsJVvI19DsdnruXtAUbnTmVmbpPz6bKHD0SPvH9kjj5VTGBiqHFPf4ONp7Ry6mjXCEbB+DlZiD4TiwTRcdZJEZ8g8zScaOc5K2Z+Md17vMws57MGvq6gH8J8w5dGHFRD+CfRmTYhhX4v8x2noB3GNb6f0vwSlTQN1Q3RLtUrLv4+ZUYcMW/pIRUo7/4CZaiGhHm4Y86lLLH+WIcSSdl5Vhhw4Nm3w29R3mdW0eViSljHCCSGX/Uyp0LrtL1uF71yNH4UPpRwObI6KENYCwSacb1WYKX90rMnlJ7I=
script:
- npm run test
env:
  global:
    secure: iCcWDJEErmvCbg0PmdQbu8545GkM1jAaBB1TWzaYymURkisZcuCa6zgDKslEAXlMEuzJ9/pA5/qQ/lknMS7+PoOyRQZE6oicSCEg9yCqQbWgMii4zx8mP0Zw5EdjDyy6vEftOJMfcDYhuzTeX5vCuglFBFc0nNWN1QK+OosQ/oo+iV/p2x3JRBBzMZkuudAAuhjMHBiG789eSrtZaFuXAJ9YcW3Yq64e9PZtZasRQwviEODEsfl/R0KUu+SZv0nY1ZpYxhKt1tEBFCc2SeqXMOijn83PU6GwrJlhO4RoX4h6JPPh27yNe/PMId338TlOW+dvaRHQDuCttdPJwtXOVjT/2iCSYW8p+f0XsmPGKYbVnJQylc8W1g9r+BocSO6yGaETIdaQnPEIWI3quiBw4JX+qtj2YWkYBIG8tc4dFwGJ1zAveboqZPUDZxJJyH+5OGV0lWzhmLwRzyQANGatkXeQ1M2soCusk3IulmEBxlGwUEkSjn6GhzDEI/NFmjkNsksE4ccHfKNMsp1N25RHN4Q7eHYsVbY3B/4eb2D1/saK9sY0zfRKwj0/MnkEv/pgQFb0KteoneXEQxr4i3eST0ECGA7jbD2HUTFIkGxRpQ7t5zL4a3HqcFsDo3zqtkVL4TEZkpZYZnZ/Q3+yVMv3SC1zZaE/nP2O+Mi3N1BFkTo=

    deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD dupa"
  skip_cleanup: true
  on:
    tags: true